# Generated by Django 5.1.1 on 2024-10-11 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupemailverficationtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
