# Generated by Django 5.1.1 on 2024-10-11 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_signupemailverficationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupemailverficationtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
